<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AuthOauth\Adapter\BaseAdapter'            => __DIR__ . '/src/AuthOauth/Adapter/BaseAdapter.php',
    'AuthOauth\Adapter\GoogleAdapter'          => __DIR__ . '/src/AuthOauth/Adapter/GoogleAdapter.php',
    'AuthOauth\Controller\AuthServiceTrait'    => __DIR__ . '/src/AuthOauth/Controller/AuthServiceTrait.php',
    'AuthOauth\Controller\IndexController'     => __DIR__ . '/src/AuthOauth/Controller/IndexController.php',
    'AuthOauth\Factory\AuthServiceFactory'     => __DIR__ . '/src/AuthOauth/Factory/AuthServiceFactory.php',
    'AuthOauth\Factory\AdapterAbstractFactory' => __DIR__ . '/src/AuthOauth/Factory/AdapterAbstractFactory.php',
    'AuthOauth\Factory\HydratorFactory'        => __DIR__ . '/src/AuthOauth/Factory/HydratorFactory.php',
    'AuthOauth\Factory\IndexControllerFactory' => __DIR__ . '/src/AuthOauth/Factory/IndexControllerFactory.php',
    'AuthOauth\Generic\Event'                  => __DIR__ . '/src/AuthOauth/Generic/Event.php',
    'AuthOauth\Generic\Constants'              => __DIR__ . '/src/AuthOauth/Generic/Constants.php',
    'AuthOauth\Generic\User'                   => __DIR__ . '/src/AuthOauth/Generic/User.php',
    'AuthOauth\Generic\Hydrator'               => __DIR__ . '/src/AuthOauth/Generic/Hydrator.php',
    'AuthOauth\Module'                         => __DIR__ . '/Module.php',
);
