<form class="form-horizontal" action="/events/doctrine/signup/<?= $event['id'] ?>" method="POST">
    <fieldset>

        <!-- Form Name -->
        <legend>Event Signup</legend>

        Please fill out all items, there is no form validation.

        <div class="control-group">
            <label class="control-label">Event</label>
            <div class="controls">
                <span class=""><?= $event['name'] ?></span>
            </div>
        </div>


        <!-- Text input-->
        <div class="control-group">
            <label class="control-label">First Name</label>
            <div class="controls">
                <input id="first_name" name="first_name" placeholder="First Name" required="" class="input-xlarge" type="text">

            </div>
        </div>

        <!-- Text input-->
        <div class="control-group">
            <label class="control-label">Last Name</label>
            <div class="controls">
                <input id="last_name" name="last_name" placeholder="Last Name" required="" class="input-xlarge" type="text">

            </div>
        </div>

        <div id="ticket-list" data-ticket-count="1">

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <button type="button" id="add-ticket" name="add-ticket" class="btn btn-primary">Add Another Ticket</button>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Name On Ticket #1</label>
                <div class="controls">
                    <input id="ticket_1" name="ticket[1]" placeholder="Name On Ticket" required="" class="input-xlarge" type="text">
                </div>
            </div>

        </div>

        <!-- Button -->
        <div class="control-group">
            <label class="control-label"></label>
            <div class="controls">
                <button id="" name="" class="btn btn-success">Sign Up!</button>
            </div>
        </div>


    </fieldset>
</form>

<script>
    $('#add-ticket').click(function() {
        ticketList = $('#ticket-list');
        numTickets = ticketList.data('ticket-count');
        nextTicketIndex = numTickets + 1;
        ticketList.append(
            '<div class="control-group">'
            + '<label class="control-label">Name On Ticket #' + nextTicketIndex + '</label>'
            + '<div class="controls"><input id="ticket_' + nextTicketIndex + '" name="ticket[' + nextTicketIndex + ']"'
            + 'placeholder="Name On Ticket" required="" class="input-xlarge" type="text"></div></div>'
        );
        ticketList.data('ticket-count', nextTicketIndex);
    });
</script>
