<?= $this->partial('events/index/breadcrumbs'); ?>
<div class="col-lg-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Table Module</h2>
        </div>
        <div class="panel-body">
            <h4>Sign Up Form</h4>
            <p><a class="btn btn-block btn-success btn-large" href="<?= $this->url('events/table-module/signup'); ?>">Signup &raquo;</a></p>
            <h4>Admin Area</h4>
            <p><a class="btn btn-block btn-primary btn-large" href="<?= $this->url('events/table-module/admin'); ?>">Admin &raquo;</a></p>
        </div>
    </div>
</div>

<div class="col-lg-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Domain Model</h2>
        </div>
        <div class="panel-body">
            <h4>Sign Up Form</h4>
            <p><a class="btn btn-block btn-success btn-large" href="<?= $this->url('events/table-module/signup'); ?>">Signup &raquo;</a></p>
            <h4>Admin Area</h4>
            <p><a class="btn btn-block btn-primary btn-large" href="<?= $this->url('events/table-module/admin'); ?>">Admin &raquo;</a></p>
        </div>
    </div>
</div>

<div class="col-lg-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Doctrine</h2>
        </div>
        <div class="panel-body">
            <h4>Sign Up Form</h4>
            <p><a class="btn btn-block btn-success btn-large" href="<?= $this->url('events/table-module/signup'); ?>">Signup &raquo;</a></p>
            <h4>Admin Area</h4>
            <p><a class="btn btn-block btn-primary btn-large" href="<?= $this->url('events/table-module/admin'); ?>">Admin &raquo;</a></p>
        </div>
    </div>
</div>
