<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Event Signup</h3>
        </div>
        <div class="panel-body">
            <?php foreach ($events as $event) : ?>
                <a href="/events/table-module/signup/<?= $event['id'] ?>"><?= $event['name'] ?></a><br />
            <?php endforeach; ?>
        </div>
    </div>
</div>
