<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Registration Information</h2>
        </div>
        <div class="panel-body">
        <?php $count = 0; ?>
        <table class="table table-striped">
            <tr><th>First</th><th>Last</th><th>Reg Date</th><th>Attendees</th></tr>
            <?php $regId = 0; ?>
            <?php foreach ($registrations as $reg): ?>
                <tr>
                <?php if ($regId !== $reg['registration_id']) : ?>
                    <?php $regId = $reg['registration_id'] ?>
                    <td><?= $reg['first_name'] ?></td>
                    <td><?= $reg['last_name'] ?></td>
                    <td><?= $reg['registration_time'] ?></td>
                <?php else : ?>
                    <td colspan=3>&nbsp;</td>
                <?php endif; ?>
                    <td><?= $reg['name_on_ticket'] ?></td>
                </tr>
            <?php endforeach; ?>
            <tr><td colspan=2>&nbsp;</td><th>Total</th><td><?= count($registrations) ?></td></tr>
        </table>
        <hr />
        </div>
    </div>
</div>
