<div class="span7">
<style>
th {
	text-align: right;
}
.listingImage {
    float: left;
    width: 40%;
    height: 800px;
}
.listingNotes {
    float: left;
    width: 60%;
}
.tableSpace {
    width: 100px;
}
</style>
<p>
<?php if ($this->item) : ?>
	<h3><i><?php echo $this->escapeHtml($this->item->title); ?></i></h3>
	<table width="60%" cellspacing="5px" cellpadding="5px">
	<tr>
	<td><h4>$<?php echo number_format($this->item->price,2); ?></h4></td>
	<td><h4><?php echo $this->escapeHtml($this->item->city); ?></h4></td>
	<td><h4><?php echo $this->escapeHtml($this->item->country); ?></h4></td>
	<td><a href="<?php echo $this->basePath(); ?>/market/delete/confirm/<?php echo (int) $this->item->listings_id; ?>">Delete</a></td>
	</tr>
	</table>
	<hr />
	<div class="listingImage">
	<?php $photoFilename = $this->escapeHtml($this->item->photo_filename); ?>
	<?php if (stripos($photoFilename, 'http:') === FALSE) $photoFilename = $this->basePath() . $photoFilename; ?>
	<img src="<?php echo  $photoFilename; ?>" width="200px"/>
	</div>
    <div class="listingNotes">
	<table cellspacing="10px" cellpadding="10px" class="tableClass">
	<tr><th>Category</th><td class="tableSpace">&nbsp;</td><td><?php echo $this->escapeHtml($this->item->category); ?></td></tr>
	<tr><th>Posted</th><td class="tableSpace">&nbsp;</td><td><?php echo $this->escapeHtml($this->item->date_created); ?></td></tr>
	<tr><th>Expires</th><td class="tableSpace">&nbsp;</td><td><?php echo $this->escapeHtml($this->item->date_expires); ?></td></tr>
	<tr><th>Name</th><td class="tableSpace">&nbsp;</td><td><?php echo $this->escapeHtml($this->item->contact_name); ?></td></tr>
	<tr><th>Phone</th><td class="tableSpace">&nbsp;</td><td><?php echo $this->escapeHtml($this->item->contact_phone); ?></td></tr>
	<tr><th>Email</th><td class="tableSpace">&nbsp;</td><td><?php echo $this->escapeHtml($this->item->contact_email); ?></td></tr>
	</table>
    </div>
    <hr>
	<p><?php echo $this->escapeHtml($this->item->description); ?></p>
	<hr />
<?php else : ?>
  	Unable to find listing!
<?php endif; ?>
</p>
</div>
