<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Signup Form</h3>
            </div>
            <div class="panel-body">
                <p>Please sign our guestbook!</p>
                <?php $this->form->prepare(); ?>
                <?= $this->form()->openTag($this->form); ?>
                <p>
                    <dt><?= $this->formLabel($this->form->get('name')); ?></dt>
                    <dd><?= $this->formText($this->form->get('name')); ?>
                        <?= $this->formElementErrors($this->form->get('name')); ?></dd>
                    <dt><?= $this->formLabel($this->form->get('email')); ?></dt>
                    <dd><?= $this->formEmail($this->form->get('email')); ?>
                        <?= $this->formElementErrors($this->form->get('email')); ?></dd>
                    <dt><?= $this->formLabel($this->form->get('website')); ?></dt>
                    <dd><?= $this->formUrl($this->form->get('website')); ?>
                        <?= $this->formElementErrors($this->form->get('website')); ?></dd>
                    <dt><?= $this->formLabel($this->form->get('message')); ?></dt>
                    <dd><?= $this->formTextarea($this->form->get('message')); ?>
                        <?= $this->formElementErrors($this->form->get('message')); ?></dd>
                    <dt><?= $this->formLabel($this->form->get('avatar')); ?></dt>
                    <dd><?= $this->formFile($this->form->get('avatar')); ?>
                        <?= $this->formElementErrors($this->form->get('avatar')); ?></dd>
                </p>
                <p><span class="btn btn-success"><?= $this->formSubmit($this->form->get('submit')); ?></span></p>
                <?= $this->form()->closeTag(); ?>

                <?php if ($this->message) : ?><b><?= $this->message; ?></b><br><?php endif; ?>
                <a href="<?php $this->url('home'); ?>">HOME</a>
                <br>
                <?php \Zend\Debug\Debug::dump($this->data, 'Request Data<br>'); ?>
                <?php \Zend\Debug\Debug::dump($this->guest, 'Guestbook Entity<br>'); ?>
            </div>
        </div>
    </div>

</div>
